files:
  - source: /src/_locales/en/messages.json
    translation: /src/_locales/%two_letters_code%/messages.json
    languages_mapping:
      two_letters_code:
        zh-CN: zh_CN
        zh-TW: zh_TW
